
SELECT * FROM myntra.products;
use myntra;

-- Showing specific rows

select sizes from products;
select discounted_price, brand_name,Product_tag FROM products;

-- RENAME TABLE products to data;
-- rename table products to datas;
-- rename table datas to products;

-- Creating a new row with mathmatical operations

SELECT Product_name,brand_name,marked_price,discounted_price,(marked_price-discounted_price) as "Discount" FROM Products;

-- creating a new column that is discount %
SELECT product_name,brand_name,marked_price,discounted_price,ROUND(((marked_price-discounted_price)/marked_price)*100,2) as'Discount %'
FROM Products;

-- CREATING MULTIPLE SUCH COLUMNS

SELECT product_name,brand_name,marked_price,discounted_price,(marked_price-discounted_price) as 'Discount',
ROUND(((marked_price-discounted_price)/marked_price)*100,1) as 'Discount%'
FROM products ;

-- Find unique brand names

SELECT DISTINCT(brand_name) from products;

-- Adding where clause
-- FIND UNIQUE PRODUCTS SERVED BY ADIDAS

SELECT distinct(Product_tag),brand_name FROM products
Where brand_name = 'Adidas' ;

-- FIND UNIQUE Products served by Adidas

  SELECT DISTINCT(product_tag),brand_tag FROM products WHERE brand_tag= 'Adidas';

-- FIND UNIQUE Products served by Adidas where discounted_price >5000

SELECT DISTINCT (Product_tag),brand_tag from products where brand_name ='Adidas' and discounted_price > 5000;
 
SELECT DISTINCT (Product_tag),brand_name from products where brand_name ='Puma' and discounted_price < 5000;
 
 -- Find unique product tag of Roadster with discounted price  between 3000 and 8000
 
 Select distinct(Product_tag),brand_tag ,discounted_price
 from products where brand_name = 'Roadster'and discounted_price>3000 and discounted_price <8000;
 
 -- Another method using between function
 
 select distinct(Product_tag),brand_tag ,discounted_price
 from products where brand_name = 'Roadster'and discounted_price between 3000 and 8000;
 
 -- Find Unqiue Product Tag of 'Roadster' with discounted price between 4000 and 8000 and rating > 3 
--  and rating count > 12

SELECT DISTINCT(product_tag), brand_tag, discounted_price
FROM products
WHERE brand_name = 'Adidas' and discounted_price between 4000 and 8000 and rating > 3 and rating_count > 12;
 
 -- find me the brnad where rating count is greater than 3000 and product tag shoukd only be 
 -- tshirt, casual shoes and flipflop
 select*from products;
 SELECT DISTINCT brand_name,rating_count,product_tag from products
 where rating_count >3000 and product_tag IN('tshirts','flip-flops');
 
 -- Find UNIQUE Product tag of brand adidas Where discounted price >5000 and Marked_Price>8000
 
 SELECT distinct(Product_tag),brand_tag, discounted_price 
 from products
 where (brand_tag ='Adidas' or brand_tag= 'Puma') and
 (discounted_price between 3000 and 8000);
 
 -- ANOTHER METHOD USING IN
 
 SELECT distinct(Product_tag),brand_tag, discounted_price 
 from products
 where brand_tag  IN('Adidas','puma') and
 (discounted_price between 3000 and 8000);
 
 -- Find Unique Products not of Brand H&M or Biba
 -- Where discounted price between 2000 and 4000
 
SELECT DISTINCT (Product_tag),brand_name,discounted_price
from products
where(brand_name='H&M' or not brand_name='Biba') and
discounted_price between 2000 and 4000;

-- ANOTHER METHOD USING NOT IN

SELECT DISTINCT (Product_tag),brand_name,discounted_price
from products
where brand_tag NOT IN ('H&M', 'Biba') and
discounted_price between 2000 and 4000;



-- find max and min price

select max(marked_price),min(marked_price) from products;
select max(Discounted_price)from products;
select*from products where discounted_price ='45900';

-- find me the brand_name where marked_price is max and min and similarly for  discounted_price as well  as

select*from products where marked_price='55';

-- max marked_price brand_name
select*from products where marked_price='113999';

-- find me the average marked_price and discounted_price
SELECT AVG(marked_price),AVG(discounted_price)From products;


select count(*)from products;

-- find most ,least expensive,average discounted and  marked price of adidas products

SELECT MAX(marked_price),MIN(marked_price),AVG(marked_price) from products
 where brand_name='adidas';
 
 SELECT MAX(marked_price),MIN(marked_price),AVG(marked_price) from products
 where brand_name='PUMA';
 
-- creating new columns of total revenue generated by each product


--  revenue rating_count*discounted_price
SELECT SUM(rating_count*discounted_price)as 'sum of revenue' from products;
 
-- Find the number of categories nike serves
SELECT COUNT(DISTINCT(PRODUCT_TAG))FROM PRODUCTS
WHERE BRAND_NAME='NIKE';

SELECT *FROM products order by discounted_price ASC LIMIT 5;
SELECT *FROM products order by discounted_price DESC LIMIT 5;

SELECT*FROM products order by rating_count  ASC LIMIT 5;


Select *,rating*rating_count from products order by rating*rating_count DESC LIMIT 5;

-- Finding the second most expensive products  on myntra


SELECT *FROM products
order by discounted_price desc limit 1,1;

SELECT *FROM products
order by discounted_price desc limit 23,3;

-- Finding the 10th least rated products
SELECT*FROM products
order by rating  asc limit 9,10;

-- finding the worst rated products by nike &rating is not zero
select*from products
where brand_name='nike' and not rating = 0
order by rating ;

-- Finding the top 10 best rated tshirts from nike or adidas\rating*rating_count
select product_tag,rating,rating_count,brand_tag,discounted_price,round(rating*rating_count)as 'comb_rating'from products
where brand_name IN ("nike","adidas") and product_tag='tshirts'
order by comb_rating desc limit 10;

-- worst rated 10 products based on the rating of 100 people atleast

SELECT product_tag,rating_count,rating from products
where rating_count >= 100
order by rating_count asc limit 20;

-- select the product in alphabetical  desending orderbased on their product_name and show the last 10 of them
select product_name from  products
order by product_name asc limit 10;


SELECT  product_tag,brand_name, discounted_price from products 
where brand_name in('nike','adidas ' ) and discounted_price between 1000 and 1200 and product_tag ='tshirts' 
order by brand_name ASC ,discounted_price ASC;




                -- GROUP BY



SELECT Brand_name ,sum(discounted_price) from products
group by brand_name ;


-- Finding the names of unique brands
SELECT distinct brand_name from products;

-- select the  number of  products in each brand
 SELECT brand_name,count(product_tag) as tag from products
 group by brand_name;


-- Top 5 brand that generate maximum revenue

select brand_name,SUM(rating_count*discounted_price)as 'sum of revenue' from products
group by brand_name order by   'sum of revenue' desc limit 5;

-- top 10 sold brand maximum products

select sum(rating_count),brand_name from products
group by brand_name order by sum(rating_count )desc limit 10;

-- top 5 category most sold along with  their revenue
-- sort based on revenue


select product_tag,sum(rating_count),sum(rating_count*discounted_price) as 'revenue'
 from products
group by product_tag order by sum(rating_count*discounted_price) desc limit 5;

-- finding the top 5 brand who has the most number of products
-- different product in their inventory

select  count(distinct(product_tag)),brand_name from products
group by brand_name order by  count(product_tag) desc limit 5;


-- finding the top 5 brand who sold most number of products

select brand_name, sum(rating_count) from products
group by brand_name order by sum(rating_count) desc limit 5;

-- finding the top 5 expensive brands based on  their discounted_price

select brand_name, AVG(discounted_price)  from products
group by brand_name order by AVG(discounted_price) desc limit 5;

-- least expensive
select brand_name,AVG(discounted_price) from products
group by brand_name order by  AVG(discounted_price) ASC limit 5;

select Product_tag ,sum(rating_count) from products
group by product_tag order by sum(rating_count) desc limit 10;


 
select brand_name,AVG((marked_price-discounted_price)/marked_price) as 'discount' from products
group by brand_name order by 'discount'  desc limit 10;

 -- other method
 
select brand_name,avg(dicount_price) from products
group by brand_name order by avg(dicount_price) desc limit 10;

select product_tag, AVG(rating_count) from products
group by product_tag order by AVG(rating_count) desc limit 5;

-- 2. which category of any specific brand is sold the most?

select product_tag,brand_name,sum(rating_count)as 'sold' from products
group by product_tag,brand_name order by sold desc;


select brand_name,product_tag,sum(rating_count)as 'sold' from products
group by brand_name,product_tag order by sold desc;

# 3. List top 5 brands which has sold most number of tshirts

SELECT brand_tag, SUM(rating_count) as sold 
FROM products
WHERE product_tag = 'tshirts'
GROUP BY brand_tag
ORDER BY sold desc LIMIT 5;


# 4. List top 5 brands which has sold most number of shirts
select brand_tag, sum(rating_Count) as 'sold_shirts'from products
where product_tag = 'shirts'
group by brand_tag order by sold_shirts desc limit 5;


# 5. List top 5 brands which has sold most number of jeans
select brand_tag , sum(rating_count) from products
where product_tag = 'jeans'
group by brand_tag  order by sum(rating_count) desc limit 5;


# 6. List top 5 brands which has sold most number of dresses
select brand_tag,count(rating_count) from products
where product_tag = 'dresses'
group by brand_tag order by count(rating_count) desc limit 5;



# 7. Most popular product name listed in Myntra

SELECT product_name, COUNT(product_name) FROM products 
GROUP BY product_name
ORDER BY COUNT(product_name) desc;

# 8. Number of products sold for every rating (0 - 5)

select rating, sum(rating_count) from products
group by rating
order by sum(rating_count) asc;

# 9. Number of products sold for every rating by bike

select rating, sum(rating_count) from products
group by rating order by sum(rating_count)  desc ;


# 10. Number of products sold for every rating in tshirts category

select rating,sum(rating_count),product_tag from products
where product_tag ='tshirts'
group by rating order by sum(rating_count) desc ;

# 11. Relation between price of the thisrts and its rating wrt to people rated
select rating,product_tag,avg(Marked_price) from products
where product_tag = 'tshirts'
group by rating order by AVG(Marked_price) desc;

