
select*from sales.sales_data;

-- Objective 1: Analyzing Sales Performance
-- What is the total sales amount generated by each sales representative?

select salesRepID, sum(Quantity) from sales_data
group by salesRepID order by sum(Quantity) desc;

-- How many products have been sold in each store location?
select storeLocation,count(quantity) from sales_data
group by storeLocation order by  count(quantity) desc;

-- Which product category has the highest total sales amount?

-- What is the average quantity of products sold per sale?
-- Which customer has made the highest number of purchases?
-- What is the distribution of total sales amounts across different months?
-- How does the sales performance of different regions compare?
-- What is the total sales amount generated for each product?
-- What is the average sales amount per transaction?
-- How many sales transactions were made by each sales representative?